version: '2.1'

services:
  component-misc-bl:
    image: component-misc-bl
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3005:3005
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js