version: '2.1'

services:
  neighboorhood:
    image: neighboorhood
    build: .
    environment:
      NODE_ENV: development
    ports:
      - 3005:3005
      - 9229:9229
    ## set your startup file here
    command: node --inspect index.js